import { WorkCard } from "../WorkCard"; 


const AdsWork = () => {
    return (
        <section className="grid md:grid-cols-2 lg:grid-cols-5 gap-3 md:gap-6 adsWork" id="ads">
            <h2 className="col-span-2 lg:col-span-1 row-span-2 --full-width aspect-[351/222] lg:aspect-[259/524] rounded-lg text-primary p-2 lg:p-4 border text-left flex justify-start items-start transition-colors duration-200  bg-primary text-white">
                <span className="items-start">
                    <span className="inline font-staatliches text-[40px] lg:text-5xl xl:text-5xl 2xl:text-[64px] leading-none lg:leading-11 xl:leading-13 2xl:leading-14 text-white">Ads</span>
                    <sup className='text-xs md:text-[16px] text-white relative -top-5 xl:-top-8 font-medium'>(19)</sup>
                </span>
            </h2>
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/0.png", mobile: "/assets/work/ads/mobile/0.png", alt: "" }} name="CaratLane" category="Ads" href="https://www.youtube.com/watch?v=iK2oPfFaIik&ab_channel=CaratLane" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" />
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/1.png", mobile: "/assets/work/ads/mobile/1.png", alt: "" }} name="Razorpay" category="Ads" href="https://www.youtube.com/watch?app=desktop&fbclid=PAAaY01bwXN2uvyHH_Aa0Fkyawh8sTtzXKQa97GbMwcunNY8zSbcNbXQCotzI&v=cQe5uK3SD1s&feature=youtu.be&ab_channel=Razorpay" grid="aspect-[170/220] lg:aspect-[826/524] col-span-1 lg:col-span-3 row-span-1 lg:row-span-2" />
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/2.png", mobile: "/assets/work/ads/mobile/2.png", alt: "" }} name="caratline" category="Ads" href="https://www.youtube.com/watch?v=Ppo8T4tKXOY&ab_channel=CaratLane" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" />
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/3.png", mobile: "/assets/work/ads/mobile/3.png", alt: "" }} name="pigeon india" category="Ads" href="https://www.youtube.com/watch?v=Cudx5RQnA3I&ab_channel=PigeonIndia" grid="col-span-1 lg:col-span-3 row-span-2 aspect-[170/220] lg:aspect-[826/524]" />
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/4.png", mobile: "/assets/work/ads/mobile/4.png", alt: "" }} name="caratlane" category="Ads" href="https://www.youtube.com/watch?v=2DZRyys1cSs&ab_channel=CaratLane" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524] bg-red-500" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/5.png", mobile: "/assets/work/ads/mobile/5.png", alt: "" }} name="RAYMOND" category="Ads" href="https://www.youtube.com/watch?v=0f4oNqvli4k&ab_channel=EthnixByRaymond" grid="col-span-1 lg:col-span-3 row-span-1 md:row-span-2 aspect-[170/220] lg:aspect-[826/524]" />
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/6.png", mobile: "/assets/work/ads/mobile/6.png", alt: "" }} name="Goel TMT" category="Ads" href="https://www.youtube.com/watch?v=JfJAvA_Tmqg&ab_channel=GOELTMT" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/7.png", mobile: "/assets/work/ads/mobile/7.png", alt: "" }} name="Raymond" category="Ads" href="https://www.instagram.com/reel/C2BtSvbod3Z/?igsh=dzZla2VxZ2hsNDdo" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/8.png", mobile: "/assets/work/ads/mobile/8.png", alt: "" }} name="Asian Paints" category="Ads" href="https://www.instagram.com/reel/DJveVt0IPM0/?igsh=d2I5dmRxMDhucWFr" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/9.png", mobile: "/assets/work/ads/mobile/9.png", alt: "" }} name="Asian Paints" category="Ads" href="https://www.instagram.com/reel/DJvmxLZIrmI/?igsh=cHB6dHZra3R0Ymky" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/10.png", mobile: "/assets/work/ads/mobile/10.png", alt: "" }} name="Asian Paints" category="Ads" href="https://www.instagram.com/reel/DJvkgEzIsf8/?igsh=MWs1cjV2eTZleDd5OA%3D%3D" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/11.png", mobile: "/assets/work/ads/mobile/11.png", alt: "" }} name="Asian Paints" category="Ads" href="https://www.instagram.com/reel/DJvfU5Oom-v/?igsh=MTFzZHg0YnM0eTR0MA%3D%3D" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/12.png", mobile: "/assets/work/ads/mobile/12.png", alt: "" }} name="Air India" category="Ads" href="https://www.instagram.com/p/C7UN8vQNC-w/" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/13.png", mobile: "/assets/work/ads/mobile/13.png", alt: "" }} name="Air India" category="Ads" href="https://www.instagram.com/reel/C84SYGUyY9C/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/14.png", mobile: "/assets/work/ads/mobile/14.png", alt: "" }} name="Asian Paints" category="Ads" href="https://www.youtube.com/watch?v=QuCFWqViV6I&ab_channel=AsianPaints" grid="col-span-1 lg:col-span-3 row-span-2 aspect-[170/220] lg:aspect-[826/524]" />  
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/15.png", mobile: "/assets/work/ads/mobile/15.png", alt: "" }} name="Federal Bank" category="Ads" href="https://www.youtube.com/watch?v=vGDEU8qb-tg&ab_channel=FederalBank" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" />
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/16.png", mobile: "/assets/work/ads/mobile/16.png", alt: "" }} name="Nippon India" category="Ads" href="https://www.youtube.com/watch?v=S8-yEMwn8a8&ab_channel=NipponIndiaMutualFund" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" /> 
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/17.png", mobile: "/assets/work/ads/mobile/17.png", alt: "" }} name="Air India" category="Ads" href="https://www.youtube.com/watch?v=ZRyIkmQL5nI&ab_channel=AirIndiaOfficial" grid="col-span-1 row-span-1 lg:row-span-2 aspect-[170/220] lg:aspect-[259/524]" />
            <WorkCard img={{ desktop: "/assets/work/ads/desktop/18.png", mobile: "/assets/work/ads/mobile/18.png", alt: "" }} name="Asian Paints" category="Ads" href="https://www.youtube.com/watch?v=dynGK7IbfsU&ab_channel=AsianPaints" grid="col-span-1 lg:col-span-3 row-span-2 --full-width aspect-[351/222] lg:aspect-[170/220] lg:aspect-[826/524]" /> 
        </section>
    )
}

export default AdsWork