import type { Metadata } from "next";
import { Staatliches } from "next/font/google";
import localFont from 'next/font/local'
import Header from "@/componets/layout/header";
import Footer from "@/componets/layout/footer";
import "./globals.css";

const staatlichesSans = Staatliches({
  variable: "--font-staatliches" ,
  weight: "400",
});

const satoshi = localFont({
  src: '../font/satoshi-variable.woff2',
  variable: "--font-satoshi",
  display: "swap",
  weight: "300 400 500 700",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${staatlichesSans.variable} ${satoshi.variable} antialiased`}
      >
        <Header />
        <main className="flex flex-col min-h-screen gap-6 px-3 md:px-6 pb-4 md:pb-6 bg-white relative z-[1] pt-20 md:pt-28">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
